packages:
  - name: scraper
    functions:
      - name: api-key-rotator
        runtime: "nodejs:18"
        limits:
          memory: 512
      - name: async-job
        runtime: "nodejs:18"
        limits:
          memory: 512
      - name: response-catch
        runtime: "nodejs:18"
        limits:
          memory: 1024
  - name: hoppler
    environment:
    functions:
      - name: condominium
        runtime: "nodejs:18"
        limits:
          memory: 512
      - name: house-and-lot
        runtime: "nodejs:18"
        limits:
          memory: 512
  - name: lamudi
    environment:
    functions:
      - name: condominium
        runtime: "nodejs:18"
        limits:
          memory: 512
      - name: house-and-lot
        runtime: "nodejs:18"
        limits:
          memory: 512
  - name: myproperty
    environment:
    functions:
      - name: condominium
        runtime: "nodejs:18"
        limits:
          memory: 512
      - name: house-and-lot
        runtime: "nodejs:18"
        limits:
          memory: 512
environment:
  LOG_DESTINATIONS: "${LOG_DESTINATIONS}"
  SCRAPER_API_KEY: "${SCRAPER_API_KEY}"
  SCRAPER_API_JOBS_URL: "${SCRAPER_API_JOBS_URL}"
  DATABASE_URL: "${DATABASE_URL}"
  PG_DATABASE_HOST: "${PG_DATABASE_HOST}"
  PG_DATABASE_PORT: "${PG_DATABASE_PORT}"
  PG_DATABASE_USER: "${PG_DATABASE_USER}"
  PG_DATABASE_PASS: "${PG_DATABASE_PASS}"
  PG_DATABASE_NAME: "${PG_DATABASE_NAME}"
  PG_SSL_MODE: "${PG_SSL_MODE}"
