packages:
  - name: scraper
    functions:
      - name: api-key-rotator
        runtime: "nodejs:18"
        limits:
          memory: 512
      - name: async-job
        runtime: "nodejs:18"
        limits:
          memory: 512
      - name: response-catch
        runtime: "nodejs:18"
        limits:
          memory: 1024
environment:
  SCRAPER_API_KEY: "${SCRAPER_API_KEY}"
  SCRAPER_API_JOBS_URL: "${SCRAPER_API_JOBS_URL}"
  PG_DATABASE_HOST: "${PG_DATABASE_HOST}"
  PG_DATABASE_PORT: "${PG_DATABASE_PORT}"
  PG_DATABASE_USER: "${PG_DATABASE_USER}"
  PG_DATABASE_PASS: "${PG_DATABASE_PASS}"
  PG_DATABASE_NAME: "${PG_DATABASE_NAME}"
  PG_SSL_MODE: "${PG_SSL_MODE}"
  LOG_DESTINATIONS: "${LOG_DESTINATIONS}"
